### ISSUE TITLE
add data for end to end test of pivot base creation

### ISSUE THREAD

**Issue by jmkerloch** [IGNF/route-graph-generator#31]
We need to have some data available to test end to end pivot base creation :

For this we could use bdtopo from IGN : https://geoservices.ign.fr/bdtopo with table:
    - `troncon_de_route`
    - `non_communication`

This should be stored as a .sql dump.

This dump could then be used in a docker-compose so the input database can be available in test.

**Comment by jmkerloch** [comment]
@lgrd @azarz can you confirm that these are the only needed tables.

**Comment by lgrd** [comment]
Where do you want to store this dump ?

**Comment by azarz** [comment]
> @lgrd @azarz can you confirm that these are the only needed tables ?

These are the only needed tables

**Comment by jmkerloch** [comment]
@lgrd this dump will be stored in this repository

**Comment by gwenandres** [comment]
Here is an example of what could be dumps needed to automate tests. 

I produce these dump doing these steps : 
 - Dowloading BDTOPO GPKG  (department 13)
 - Loading tables (troncon_de_route, non_communication, arrondissement_municipal)
 - Create two tables extracting troncon_de_route and non_communication on Marseille 10ème
 - Dump this 2 tables (in dump format, lighter than sql format)


[dumps.zip](https://github.com/IGNF/route-graph-generator/files/10695934/dumps.zip)

**Comment by lgrd** [comment]
Thanks for the dump ! Have you already used it for a generation ?

**Comment by gwenandres** [comment]
I use the entire PACA data for my first test. Then I make this subset and @jmkerloch use it for generation. 

@jmkerloch  here are dumps in sql format

[dumps_sql.zip](https://github.com/IGNF/route-graph-generator/files/10744559/dumps_sql.zip)

**Comment by azarz** [comment]
> Sure, but what URL should we use? We can't seriously rely on the actual delivery service of BDTopo...

Is the link to the dump uploaded here by @gwenandres permanent? If so, we could maybe use that in the CI 🤷 
https://github.com/IGNF/route-graph-generator/files/10744559/dumps_sql.zip

**Comment by lgrd** [comment]
You can also use https://storage.gra.cloud.ovh.net/v1/AUTH_366279ce616242ebb14161b7991a8461/road2/dumps.zip which is an object storage of IGN. It is a temporary solution until we have a the "entrepot" and all its services.
