### ISSUE TITLE
Use schema for pivot to osm and pivot to pgr

### ISSUE THREAD

**Issue by jmkerloch** [IGNF/route-graph-generator#34]
Hi ! I've just seen that schemas are not used for the pivot in _pivot_to_osm.py and _pivot_to_pgr.py. They are used only for the final pgr base. So, if we don't change that, your modification will not be used in the next step of the generation. :/

Do you want to make the changes ? For information, I can help, but only in one or two weeks. Now, I have to make continue my work on the admin API.

_Originally posted by @lgrd in https://github.com/IGNF/route-graph-generator/issues/33#issuecomment-1435219982_

**Comment by jmkerloch** [comment]
@lgrd I will check that as soon as possible. Will you be able to review a PR ?

**Comment by lgrd** [comment]
> @lgrd I will check that as soon as possible. Will you be able to review a PR ?

Yes I will be able to do it on Monday. I’ve seen what you’ve done. But I can’t test it this week with data.
